{
    "name": "ATT Transport Order",
    "version": "19.0.1.0.0",
    "category": "Inventory/Delivery",
    "summary": "Lệnh điều vận / Transport Order Trang Huy",
    "author": "Hoa.Luu ATT system Viet Nam",
    "depends": [
        "sale_management",
        "purchase",
        "account",
        "fleet",
        "hr",
        "mail",
        "att_fleet_extend",
        # "att_transport_base",
    ],
    "data": [
        "security/transport_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/ir_config_parameter.xml",
        "data/cost_type_data.xml",
        "views/transport_order_views.xml",
        "views/transport_cost_views.xml",
        "views/transport_route_views.xml",
        "views/sale_order_views.xml",
        "views/purchase_order_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}