{
    'name': 'ATT Contract Management',
    'version': '19.0.1.0.0',
    'category': 'Sales/Purchase',
    'summary': 'ATT Quotation & Contract Management — quản lý báo giá, hợp đồng khung, phụ lục',
    'description': """
Tầng nền quản lý vòng đời báo giá & hợp đồng cho Trang Huy Logistics.
    """,
    'author': 'Hoa.Luu ATT system Viet Nam',
    'license': 'LGPL-3',
    'depends': [
        'sale_management',
        'purchase',
        'account',
        'mail',
    ],
    'data': [
    'security/att_security.xml',
    'security/ir.model.access.csv',
    'data/ir_sequence.xml',
    'data/product_data.xml',
    'data/contract_clauses.xml',
    'data/ir_cron.xml',
    'wizard/att_send_document_wizard_views.xml',
    'views/res_company_views.xml',
    'views/att_sale_quotation_views.xml',
    'views/sale_order_views.xml',
    'views/att_purchase_quotation_views.xml',
    'views/purchase_order_views.xml',
    'views/att_contract_views.xml',
    'views/att_contract_clause_views.xml',
    'views/att_contract_liquidation_reason_views.xml',
    'views/att_contract_appendix_views.xml',
    'data/report_paperformat.xml',
    'reports/att_report_layout.xml',
    'reports/att_contract_report.xml',
    'reports/att_appendix_report.xml',
    'data/mail_templates.xml',
],
    'installable': True,
    'application': False,
}