{
    "name": "ATT Transport Orders",
    "version": "19.0.1.0.0",
    "category": "Inventory/Delivery",
    "summary": "Lệnh điều vận Trang Huy — tách lớp vận tải, độc lập khỏi Hợp đồng/Báo giá",
    "author": "Hoa.Luu ATT system Viet Nam",
    "depends": [
        "sale_management",
        "purchase",
        "account",
        "fleet",
        "hr",
        "mail",
        "website",
        "att_fleets_extend",
        "att_contract_management",
        "att_vietmap_connector",
    ],
    "data": [
        "security/transport_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/ir_config_parameter.xml",
        "data/cost_type_data.xml",
        "data/transport_mode_data.xml",
        "views/transport_order_views.xml",
        "views/transport_cost_views.xml",
        "views/transport_route_views.xml",
        "views/sale_order_views.xml",
        "views/purchase_order_views.xml",
        "views/att_contract_appendix_views.xml",
        "views/website_service_templates.xml",
        "views/menu_views.xml",
        "views/dispatch_dashboard_views.xml",
        "reports/sale_report_inherit.xml",
        "data/dispatch_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "att_transport_orders/static/src/js/dispatch_dashboard.js",
            "att_transport_orders/static/src/xml/dispatch_dashboard.xml",
            "att_transport_orders/static/src/scss/dispatch_dashboard.scss",
            "att_transport_orders/static/src/js/realtime_heatmap.js",
            "att_transport_orders/static/src/xml/realtime_heatmap.xml",
            "att_transport_orders/static/src/scss/realtime_heatmap.scss",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
