{
    "name": "Zegal Flow",
    "version": "19.0.1.0.0",
    "summary": "Approval, purchase, and project document flow",
    "category": "Operations",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "sale_management",
        "purchase",
        "stock",
        "project",
        "documents",
    ],
    "data": [
        "data/sequence.xml",
        "security/ir.model.access.csv",
        "views/approval_matrix_views.xml",
        "views/approval_request_views.xml",
        "views/sale_order_views.xml",
        "views/purchase_order_views.xml",
        "views/project_views.xml",
        "views/purchase_request_views.xml",
        "views/vendor_quote_views.xml",
        "views/subcontract_views.xml",
        "views/material_request_views.xml",
        "views/project_document_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
